Repository Infisical/infisical, pull requests merged in 2023-07, with the labels that each got.

#713 secret reference
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/v2/secretsController.ts
  backend/src/controllers/v2/serviceTokenDataController.ts
  backend/src/helpers/secrets.ts
  backend/src/models/serviceTokenData.ts
  backend/src/routes/v2/serviceTokenData.ts
  backend/src/utils/setup/backfillData.ts
  backend/src/utils/setup/index.ts
  backend/src/validation/serviceTokenData.ts
  cli/packages/api/model.go
  cli/packages/cmd/export.go
  cli/packages/cmd/run.go
  cli/packages/cmd/secrets.go
  cli/packages/util/log.go
  cli/packages/util/secrets.go
  docs/documentation/platform/folder.mdx
  docs/documentation/platform/secret-reference.mdx
  docs/images/project-folder-token.png
  docs/integrations/platforms/kubernetes.mdx
  docs/mint.json
  frontend/src/hooks/api/serviceTokens/types.ts
  frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/AddServiceTokenModal.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/ServiceTokenSection.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/ServiceTokenTable.tsx
  helm-charts/secrets-operator/Chart.yaml
  helm-charts/secrets-operator/templates/infisicalsecret-crd.yaml
  k8-operator/api/v1alpha1/infisicalsecret_types.go
  k8-operator/api/v1alpha1/zz_generated.deepcopy.go
  k8-operator/config/crd/bases/secrets.infisical.com_infisicalsecrets.yaml
  k8-operator/config/samples/sample.yaml
  k8-operator/controllers/infisicalsecret_helper.go
  k8-operator/kubectl-install/install-secrets-operator.yaml
  k8-operator/packages/util/secrets.go
Labels: UI, backend, cli

#711 fix: enable users to press `Enter` in forms
  frontend/src/components/login/InitialLoginStep.tsx
  frontend/src/components/signup/CodeInputStep.tsx
  frontend/src/components/signup/EnterEmailStep.tsx
  frontend/src/components/signup/UserInfoStep.tsx
  frontend/src/pages/password-reset.tsx
  frontend/src/pages/verify-email.tsx
Labels: 🐞 bug

#733 Feat/webhooks
  backend/src/controllers/v1/index.ts
  backend/src/controllers/v1/integrationController.ts
  backend/src/controllers/v1/secretController.ts
  backend/src/controllers/v1/webhookController.ts
  backend/src/controllers/v2/secretsController.ts
  backend/src/controllers/v2/workspaceController.ts
  backend/src/controllers/v3/secretsController.ts
  backend/src/events/index.ts
  backend/src/events/integration.ts
  backend/src/events/secret.ts
  backend/src/helpers/event.ts
  backend/src/index.ts
  backend/src/models/webhooks.ts
  backend/src/routes/v1/index.ts
  backend/src/routes/v1/webhook.ts
  backend/src/routes/v2/secrets.ts
  backend/src/services/WebhookService.ts
  backend/src/variables/event.ts
  docs/documentation/platform/webhooks.mdx
  docs/images/webhooks.png
  docs/mint.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translations.json
  frontend/src/components/v2/Button/Button.tsx
  frontend/src/components/v2/Tooltip/Tooltip.tsx
  frontend/src/hooks/api/index.tsx
  frontend/src/hooks/api/types.ts
  frontend/src/hooks/api/webhooks/index.tsx
  frontend/src/hooks/api/webhooks/mutation.tsx
  frontend/src/hooks/api/webhooks/query.tsx
  frontend/src/hooks/api/webhooks/types.ts
  frontend/src/views/DashboardPage/DashboardPage.tsx
  frontend/src/views/Settings/ProjectSettingsPage/ProjectSettingsPage.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/ProjectTabGroup/ProjectTabGroup.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/ProjectTabGroup/index.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/AddWebhookForm.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/WebhooksTab.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/index.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/index.tsx
Labels: UI, backend

#758 Implemented secret link/import feature
  backend/src/controllers/v1/index.ts
  backend/src/controllers/v1/secretImportController.ts
  backend/src/controllers/v2/secretsController.ts
  backend/src/controllers/v3/secretsController.ts
  backend/src/index.ts
  backend/src/models/secretImports.ts
  backend/src/routes/v1/index.ts
  backend/src/routes/v1/secretImport.ts
  backend/src/routes/v2/secrets.ts
  backend/src/routes/v3/secrets.ts
  backend/src/services/SecretImportService.ts
  backend/src/services/index.ts
  cli/packages/api/api.go
  cli/packages/api/model.go
  cli/packages/cmd/run.go
  cli/packages/cmd/secrets.go
  cli/packages/models/cli.go
  cli/packages/util/secrets.go
  docs/documentation/platform/secret-reference.mdx
  docs/images/secret-import-add.png
  docs/images/secret-import-change-order.png
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/api/index.tsx
  frontend/src/hooks/api/secretImports/index.ts
  frontend/src/hooks/api/secretImports/mutation.tsx
  frontend/src/hooks/api/secretImports/queries.tsx
  frontend/src/hooks/api/secretImports/types.ts
  frontend/src/hooks/api/secrets/queries.tsx
  frontend/src/hooks/api/secrets/types.ts
  frontend/src/views/DashboardPage/DashboardPage.tsx
  frontend/src/views/DashboardPage/components/FolderSection/FolderSection.tsx
  frontend/src/views/DashboardPage/components/SecretImportForm/SecretImportForm.tsx
  frontend/src/views/DashboardPage/components/SecretImportForm/index.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportItem.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportSection.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/index.tsx
  frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx
Labels: UI, backend, cli

#762 fix: resolved empty secrets on fresh env and added empty states
  backend/src/services/SecretImportService.ts
  frontend/src/views/DashboardPage/DashboardPage.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportItem.tsx
Labels: 🐞 bug

#764 made include_imports optional in raw secrets fetch
  backend/src/routes/v3/secrets.ts
Labels: 🐞 bug

#784 fix: resolved secret import delete and include_import response control
  backend/src/controllers/v1/secretImportController.ts
  backend/src/controllers/v2/secretsController.ts
  backend/src/controllers/v3/secretsController.ts
  backend/src/routes/v1/secretImport.ts
Labels: 🐞 bug

#793 Feat/new overview page
  backend/src/controllers/v1/secretImportController.ts
  backend/src/helpers/secrets.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/navigation/NavHeader.tsx
  frontend/src/components/v2/SecretInput/SecretInput.tsx
  frontend/src/components/v2/SecretInput/index.tsx
  frontend/src/components/v2/Table/Table.stories.tsx
  frontend/src/components/v2/Table/Table.tsx
  frontend/src/components/v2/index.tsx
  frontend/src/hooks/api/secretFolders/index.tsx
  frontend/src/hooks/api/secretFolders/queries.tsx
  frontend/src/hooks/api/secretFolders/types.ts
  frontend/src/hooks/api/secrets/index.ts
  frontend/src/hooks/api/secrets/mutations.tsx
  frontend/src/hooks/api/secrets/queries.tsx
  frontend/src/hooks/api/secrets/types.ts
  frontend/src/layouts/AppLayout/AppLayout.tsx
  frontend/src/pages/org/[id]/overview/index.tsx
  frontend/src/pages/project/[id]/secrets/[env].tsx
  frontend/src/pages/project/[id]/secrets/overview.tsx
  frontend/src/styles/globals.css
  frontend/src/views/DashboardPage/DashboardEnvOverview.tsx
  frontend/src/views/DashboardPage/DashboardPage.tsx
  frontend/src/views/DashboardPage/DashboardPage.utils.ts
  frontend/src/views/DashboardPage/components/EnvComparisonRow/EnvComparisonRow.tsx
  frontend/src/views/DashboardPage/components/EnvComparisonRow/FolderComparisonRow.tsx
  frontend/src/views/DashboardPage/components/EnvComparisonRow/index.tsx
  frontend/src/views/DashboardPage/components/FolderSection/FolderSection.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportItem.tsx
  frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportSection.tsx
  frontend/src/views/DashboardPage/components/SecretInputRow/MaskedInput.tsx
  frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx
  frontend/src/views/Org/MembersPage/components/OrgIncidentContactsTable/OrgIncidentContactsTable.tsx
  frontend/src/views/Org/MembersPage/components/OrgMembersTable/OrgMembersTable.tsx
  frontend/src/views/Org/MembersPage/components/OrgServiceAccountsTable/OrgServiceAccountsTable.tsx
  frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
  frontend/src/views/SecretOverviewPage/components/FolderBreadCrumbs/FolderBreadCrumbs.tsx
  frontend/src/views/SecretOverviewPage/components/FolderBreadCrumbs/index.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewFolderRow/SecretOverviewFolderRow.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewFolderRow/index.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/index.tsx
  frontend/src/views/SecretOverviewPage/index.tsx
  frontend/src/views/SecretScanning/components/SecretScanningLogsTable.tsx
  frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/CurrentPlanSection.tsx
  frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/ManagePlansTable.tsx
  frontend/src/views/Settings/BillingSettingsPage/components/BillingDetailsTab/PmtMethodsTable.tsx
  frontend/src/views/Settings/BillingSettingsPage/components/BillingDetailsTab/TaxIDTable.tsx
  frontend/src/views/Settings/BillingSettingsPage/components/BillingReceiptsTab/InvoicesTable.tsx
  frontend/src/views/Settings/CreateServiceAccountPage/components/SAProjectLevelPermissionsTable/SAProjectLevelPermissionsTable.tsx
  frontend/src/views/Settings/OrgSettingsPage/components/OrgIncidentContactsSection/OrgIncidentContactsTable.tsx
  frontend/src/views/Settings/OrgSettingsPage/components/OrgServiceAccountsTable/OrgServiceAccountsTable.tsx
  frontend/src/views/Settings/PersonalSettingsPage/APIKeySection/APIKeyTable.tsx
  frontend/src/views/Settings/PersonalSettingsPage/SessionsSection/SessionsTable.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/EnvironmentSection/EnvironmentTable.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/SecretTagsSection/SecretTagsTable.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/ServiceTokenTable.tsx
  frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/WebhooksTab.tsx
Labels: 🐞 bug, 🚀 feature request

#800 feat: fixed padding, added progress bar for routing, added sticky hea…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/v2/EmptyState/EmptyState.tsx
  frontend/src/components/v2/SecretInput/SecretInput.tsx
  frontend/src/components/v2/Table/Table.tsx
  frontend/src/components/v2/Table/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/styles/globals.css
  frontend/src/views/DashboardPage/DashboardPage.tsx
  frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewFolderRow/SecretOverviewFolderRow.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
  frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx
Labels: 🐞 bug, 🚀 feature request

#802 feat: added loading state for org overview page
  frontend/src/pages/org/[id]/overview/index.tsx
Labels: 🐞 bug, UI
