Repository Infisical/infisical, pull requests merged in 2024-01, with the labels that each got.

#1274 Fix: Vercel integration preview environment client side error
  frontend/src/pages/integrations/vercel/create.tsx
Labels: 🐞 bug

#1279 Contribution guide refactor & SDK contribution guide
  README.md
  docs/contributing/getting-started/code-of-conduct.mdx
  docs/contributing/getting-started/faq.mdx
  docs/contributing/getting-started/overview.mdx
  docs/contributing/getting-started/pull-requests.mdx
  docs/contributing/platform/developing.mdx
  docs/contributing/sdk/developing.mdx
  docs/images/sdk-flow.png
  docs/mint.json
Labels: 📑 documentation

#1295 fix(secret-reference): fixed undefined if value not found
  backend/src/helpers/secrets.ts
Labels: 🐞 bug

#1303 (Docs): SDK SEO Improvements & links to packages/repos
  docs/sdks/languages/csharp.mdx
  docs/sdks/languages/java.mdx
  docs/sdks/languages/node.mdx
  docs/sdks/languages/python.mdx
Labels: 📑 documentation

#1313 feat(infisical-pg): added migration mode env and page
  backend/src/config/index.ts
  backend/src/config/serverConfig.ts
  backend/src/controllers/v1/adminController.ts
  backend/src/index.ts
  frontend/public/images/maintenance.png
  frontend/src/context/ServerConfigContext/ServerConfigContext.tsx
  frontend/src/hooks/api/admin/types.ts
  frontend/src/views/admin/SignUpPage/SignUpPage.tsx
Labels: 🚀 feature request

#1346 fix: resolved encoding issue in multi line input
  frontend/src/components/v2/SecretInput/SecretInput.tsx
Labels: 🐞 bug
