Repository Infisical/infisical, pull requests merged in 2024-05, with the labels that each got.

#1776 doc: resolved missing bulk secret api operations
  docs/mint.json
Labels: 📑 documentation

#1721 Audit log streams
  backend/src/@types/fastify.d.ts
  backend/src/@types/knex.d.ts
  backend/src/db/migrations/20240503101144_audit-log-stream.ts
  backend/src/db/schemas/audit-log-streams.ts
  backend/src/db/schemas/index.ts
  backend/src/db/schemas/models.ts
  backend/src/ee/routes/v1/audit-log-stream-router.ts
  backend/src/ee/routes/v1/index.ts
  backend/src/ee/services/audit-log-stream/audit-log-stream-dal.ts
  backend/src/ee/services/audit-log-stream/audit-log-stream-service.ts
  backend/src/ee/services/audit-log-stream/audit-log-stream-types.ts
  backend/src/ee/services/audit-log/audit-log-queue.ts
  backend/src/ee/services/license/licence-fns.ts
  backend/src/ee/services/license/license-types.ts
  backend/src/lib/api-docs/constants.ts
  backend/src/lib/config/env.ts
  backend/src/lib/types/index.ts
  backend/src/lib/validator/index.ts
  backend/src/lib/validator/validate-url.ts
  backend/src/server/routes/index.ts
  backend/src/server/routes/sanitizedSchemas.ts
  docs/documentation/platform/audit-log-streams.mdx
  docs/images/platform/audit-log-streams/betterstack-create-source.png
  docs/images/platform/audit-log-streams/betterstack-source-details.png
  docs/images/platform/audit-log-streams/data-create-api-key.png
  docs/images/platform/audit-log-streams/data-dog-api-key.png
  docs/images/platform/audit-log-streams/datadog-api-sidebar.png
  docs/images/platform/audit-log-streams/datadog-logging-endpoint.png
  docs/images/platform/audit-log-streams/datadog-source-details.png
  docs/images/platform/audit-log-streams/stream-create.png
  docs/images/platform/audit-log-streams/stream-inputs.png
  docs/images/platform/audit-log-streams/stream-list.png
  docs/mint.json
  frontend/src/hooks/api/auditLogStreams/index.tsx
  frontend/src/hooks/api/auditLogStreams/mutations.tsx
  frontend/src/hooks/api/auditLogStreams/queries.tsx
  frontend/src/hooks/api/auditLogStreams/types.ts
  frontend/src/hooks/api/index.tsx
  frontend/src/hooks/api/subscriptions/types.ts
  frontend/src/hooks/api/types.ts
  frontend/src/views/Settings/OrgSettingsPage/components/AuditLogStreamTab/AuditLogStreamForm.tsx
  frontend/src/views/Settings/OrgSettingsPage/components/AuditLogStreamTab/AuditLogStreamTab.tsx
  frontend/src/views/Settings/OrgSettingsPage/components/AuditLogStreamTab/index.tsx
  frontend/src/views/Settings/OrgSettingsPage/components/OrgTabGroup/OrgTabGroup.tsx
  frontend/src/views/Settings/ProjectSettingsPage/ProjectSettingsPage.tsx
Labels: 🚀 feature request

#1782 Privilege identity api change
  backend/src/ee/routes/v1/identity-project-additional-privilege-router.ts
  backend/src/ee/services/identity-project-additional-privilege/identity-project-additional-privilege-service.ts
  backend/src/lib/api-docs/constants.ts
  backend/src/server/routes/sanitizedSchemas.ts
  frontend/package-lock.json
  frontend/src/components/v2/SecretPathInput/SecretPathInput.tsx
  frontend/src/hooks/api/identityProjectAdditionalPrivilege/queries.tsx
  frontend/src/hooks/api/roles/types.ts
  frontend/src/views/Project/MembersPage/components/IdentityTab/components/IdentityRoleForm/SpecificPrivilegeSection.tsx
  frontend/src/views/Project/MembersPage/components/MemberListTab/MemberRoleForm/SpecificPrivilegeSection.tsx
Labels: 🐞 bug, 📑 documentation

#1809 Workspace slug support in secret v3 Get Key
  backend/src/lib/api-docs/constants.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/identity-ua/identity-ua-service.ts
  backend/src/services/secret/secret-service.ts
  backend/src/services/secret/secret-types.ts
Labels: 🚀 feature request

#1818 Improvised secret input component and fontawesome performance improvment
  frontend/src/components/navigation/NavHeader.tsx
  frontend/src/components/v2/FontAwesomeSymbol/FontAwesomeSymbol.tsx
  frontend/src/components/v2/FontAwesomeSymbol/index.tsx
  frontend/src/components/v2/InfisicalSecretInput/InfisicalSecretInput.tsx
  frontend/src/components/v2/SecretInput/SecretInput.tsx
  frontend/src/components/v2/index.tsx
  frontend/src/styles/globals.css
  frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
  frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
  frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts
Labels: 👀 frontend

#1829 Revoke access token endpoint
  backend/src/lib/api-docs/constants.ts
  backend/src/server/routes/v1/identity-access-token-router.ts
  backend/src/services/identity-access-token/identity-access-token-service.ts
  docs/api-reference/endpoints/universal-auth/revoke-access-token.mdx
  docs/mint.json
Labels: 🚀 feature request

#1853 Docs: Jenkins Plugin
  docs/images/integrations/jenkins/plugin/add-infisical-secret.png
  docs/images/integrations/jenkins/plugin/install-plugin.png
  docs/images/integrations/jenkins/plugin/pipeline-configuration.png
  docs/images/integrations/jenkins/plugin/pipeline-syntax-highlight.png
  docs/images/integrations/jenkins/plugin/plugin-checked.png
  docs/images/integrations/jenkins/plugin/universal-auth-credential.png
  docs/integrations/cicd/jenkins.mdx
Labels: 📑 documentation

#1882 Docs: Azure & Kubernetes auth SDK documentation
  docs/documentation/guides/node.mdx
  docs/sdks/languages/csharp.mdx
  docs/sdks/languages/java.mdx
  docs/sdks/languages/node.mdx
  docs/sdks/languages/python.mdx
Labels: 📑 documentation

#1860 docs: updated the cause of option1 and option2 in role update commit
  backend/src/lib/api-docs/constants.ts
Labels: 📑 documentation

#1775 Secret replication
  backend/e2e-test/mocks/keystore.ts
  backend/src/@types/fastify.d.ts
  backend/src/db/migrations/20240529111503_secret-replication.ts
  backend/src/db/schemas/secret-approval-requests.ts
  backend/src/db/schemas/secret-folders.ts
  backend/src/db/schemas/secret-imports.ts
  backend/src/ee/routes/v1/secret-approval-request-router.ts
  backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
  backend/src/ee/services/secret-approval-request/secret-approval-request-types.ts
  backend/src/ee/services/secret-replication/secret-replication-constants.ts
  backend/src/ee/services/secret-replication/secret-replication-dal.ts
  backend/src/ee/services/secret-replication/secret-replication-service.ts
  backend/src/ee/services/secret-replication/secret-replication-types.ts
  backend/src/ee/services/secret-snapshot/secret-snapshot-service.ts
  backend/src/keystore/keystore.ts
  backend/src/lib/red-lock/index.ts
  backend/src/queue/queue-service.ts
  backend/src/server/routes/index.ts
  backend/src/server/routes/v1/secret-import-router.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/secret-folder/secret-folder-dal.ts
  backend/src/services/secret-folder/secret-folder-service.ts
  backend/src/services/secret-folder/secret-folder-types.ts
  backend/src/services/secret-folder/secret-folder-version-dal.ts
  backend/src/services/secret-import/secret-import-dal.ts
  backend/src/services/secret-import/secret-import-fns.ts
  backend/src/services/secret-import/secret-import-service.ts
  backend/src/services/secret-import/secret-import-types.ts
  backend/src/services/secret/secret-fns.ts
  backend/src/services/secret/secret-queue.ts
  backend/src/services/secret/secret-service.ts
  backend/src/services/secret/secret-types.ts
  backend/src/services/secret/secret-version-dal.ts
  frontend/src/hooks/api/secretApprovalRequest/queries.tsx
  frontend/src/hooks/api/secretApprovalRequest/types.ts
  frontend/src/hooks/api/secretFolders/types.ts
  frontend/src/hooks/api/secretImports/index.ts
  frontend/src/hooks/api/secretImports/mutation.tsx
  frontend/src/hooks/api/secretImports/types.ts
  frontend/src/lib/fn/string.ts
  frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx
  frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx
  frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
  frontend/src/views/SecretMainPage/components/ActionBar/CreateSecretImportForm.tsx
  frontend/src/views/SecretMainPage/components/SecretImportListView/SecretImportItem.tsx
  frontend/src/views/SecretMainPage/components/SecretImportListView/SecretImportListView.tsx
  frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
  frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts
Labels: 🚀 feature request
