Repository Infisical/infisical, pull requests merged in 2024-11, with the labels that each got.

#2685 fix: resolved tag update not happening via approval
  backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
  frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestChangeItem.tsx
Labels: 🐞 bug

#2707 feat: added tag support on create secret
  frontend/src/hooks/api/secrets/mutations.tsx
  frontend/src/hooks/api/secrets/types.ts
  frontend/src/views/SecretMainPage/SecretMainPage.tsx
  frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
  frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
  frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
Labels: 👀 frontend

#1076 feat: infisical cli for npm
  .github/workflows/release_build_infisical_cli.yml
  .gitignore
  docs/cli/overview.mdx
  npm/.eslintrc.json
  npm/README.md
  npm/package-lock.json
  npm/package.json
  npm/src/index.cjs
Labels: low-priority

#2793 feat: resolved saml failing when signup is disabled
  backend/src/server/routes/v3/signup-router.ts
  backend/src/services/auth/auth-signup-service.ts
Labels: Bug

#2817 feat: removed unusued permission from org admin
  backend/src/ee/services/permission/org-permission.ts
Labels: 🐞 bug
