Repository Infisical/infisical, pull requests merged in 2024-04, with the labels that each got.

#1644 AWS SSM integration api documentation
  backend/src/lib/api-docs/constants.ts
  backend/src/server/routes/v1/integration-auth-router.ts
  backend/src/server/routes/v1/integration-router.ts
  backend/src/server/routes/v1/project-router.ts
  docs/api-reference/endpoints/integrations/create-auth.mdx
  docs/api-reference/endpoints/integrations/create.mdx
  docs/api-reference/endpoints/integrations/delete-auth-by-id.mdx
  docs/api-reference/endpoints/integrations/delete-auth.mdx
  docs/api-reference/endpoints/integrations/delete.mdx
  docs/api-reference/endpoints/integrations/find-auth.mdx
  docs/api-reference/endpoints/integrations/list-auth.mdx
  docs/api-reference/endpoints/integrations/update.mdx
  docs/mint.json
Labels: 📑 documentation

#1643 fix(server): added sync secret for imports and added check for avoid cyclic import
  backend/e2e-test/routes/v1/secret-import.spec.ts
  backend/src/queue/queue-service.ts
  backend/src/server/routes/index.ts
  backend/src/services/secret-folder/secret-folder-dal.ts
  backend/src/services/secret-import/secret-import-dal.ts
  backend/src/services/secret-import/secret-import-service.ts
  backend/src/services/secret/secret-queue.ts
Labels: 🐞 bug

#1683 fix: resolved slow audit log list
  backend/src/ee/routes/v1/project-router.ts
  backend/src/lib/fn/dates.ts
  backend/src/lib/fn/index.ts
  frontend/src/views/Project/AuditLogsPage/components/LogsSection.tsx
Labels: 🐞 bug

#1689 Dynamic secret mysql support
  backend/src/ee/services/dynamic-secret-lease/dynamic-secret-lease-service.ts
  backend/src/ee/services/dynamic-secret/providers/models.ts
  backend/src/ee/services/dynamic-secret/providers/sql-database.ts
  frontend/src/hooks/api/dynamicSecret/types.ts
  frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx
  frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx
Labels: 🚀 feature request

#1687 docs: added aws amplify integration documentation
  docs/images/integrations/aws/integrations-amplify-app-id.png
  docs/images/integrations/aws/integrations-amplify-env-console.png
  docs/integrations/cloud/aws-amplify.mdx
  docs/mint.json
Labels: 📑 documentation

#1684 chore: rolling migration removed role and roleId field from project membership and identity project membership
  backend/.eslintrc.js
  backend/src/db/migrations/20240414192520_drop-role-roleid-project-membership.ts
  backend/src/db/schemas/identity-project-memberships.ts
  backend/src/db/schemas/project-memberships.ts
  backend/src/db/seeds/3-project.ts
  backend/src/db/seeds/4-machine-identity.ts
  backend/src/ee/services/permission/permission-dal.ts
  backend/src/server/routes/v1/project-membership-router.ts
  backend/src/server/routes/v1/project-router.ts
  backend/src/services/identity-project/identity-project-service.ts
  backend/src/services/project/project-queue.ts
  backend/src/services/project/project-service.ts
  docker-compose.dev.yml
Labels: chore

#1700 feat(cli): added template feature to cli export command
  cli/packages/cmd/agent.go
  cli/packages/cmd/export.go
  docs/cli/commands/export.mdx
Labels: 🚀 feature request

#1696 feat: dynamic secret for oracle
  backend/package-lock.json
  backend/package.json
  backend/src/ee/services/dynamic-secret/providers/models.ts
  backend/src/ee/services/dynamic-secret/providers/sql-database.ts
  frontend/src/hooks/api/dynamicSecret/types.ts
  frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx
  frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx
Labels: 🧨 backend

#1717 Fix: Frontend roles bug
  backend/src/ee/routes/v1/project-role-router.ts
  frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx
  frontend/src/context/ProjectPermissionContext/ProjectPermissionContext.tsx
  frontend/src/hooks/api/roles/queries.tsx
  frontend/src/hooks/api/users/types.ts
Labels: 🐞 bug

#1712 Batch raw secrets api
  backend/e2e-test/routes/v3/secrets.spec.ts
  backend/src/lib/api-docs/constants.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/secret/secret-service.ts
  backend/src/services/secret/secret-types.ts
  docs/api-reference/endpoints/secrets/create-many.mdx
  docs/api-reference/endpoints/secrets/delete-many.mdx
  docs/api-reference/endpoints/secrets/update-many.mdx
Labels: 📑 documentation, 🧨 backend

#1720 docs: added -y flag in infisical cli installation in amplify doc to skip confirmation prompt
  docs/integrations/cloud/aws-amplify.mdx
Labels: 📑 documentation

#1737 feat: github action to rename new migration file to latest timestamp
  .github/resources/rename_migration_files.py
  .github/workflows/update-be-new-migration-latest-timestamp.yml
Labels: 🚀 feature request, chore

#1759 fix(server): added index for audit log to resolve high latency or timeout
  backend/src/db/migrations/20240429154610_audit-log-index.ts
Labels: 🐞 bug

#1731 Dynamic secret AWS IAM
  backend/src/ee/services/dynamic-secret/providers/aws-iam.ts
  backend/src/ee/services/dynamic-secret/providers/index.ts
  backend/src/ee/services/dynamic-secret/providers/models.ts
  docs/documentation/platform/dynamic-secrets/aws-iam.mdx
  docs/images/platform/dynamic-secrets/dynamic-secret-modal-aws-iam.png
  docs/images/platform/dynamic-secrets/dynamic-secret-setup-modal-aws-iam.png
  docs/images/platform/dynamic-secrets/lease-values-aws-iam.png
  docs/mint.json
  frontend/src/hooks/api/dynamicSecret/types.ts
  frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/AwsIamInputForm.tsx
  frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/CreateDynamicSecretForm.tsx
  frontend/src/views/SecretMainPage/components/DynamicSecretListView/CreateDynamicSecretLease.tsx
  frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretAwsIamForm.tsx
  frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretForm.tsx
Labels: 🚀 feature request
