Repository Infisical/infisical, pull requests merged in 2024-02, with the labels that each got.

#1363 feat: enabled order by desc for audit log and added sort for couple of get queries
  backend/src/ee/services/audit-log/audit-log-dal.ts
  backend/src/services/secret-tag/secret-tag-service.ts
  backend/src/services/service-token/service-token-service.ts
  backend/src/services/webhook/webhook-dal.ts
Labels: 🧨 backend

#1373 feat: fixed server cfg stale in replication
  backend/src/db/instance.ts
  backend/src/ee/routes/v1/saml-router.ts
  backend/src/main.ts
  backend/src/server/boot-strap-check.ts
  backend/src/server/routes/index.ts
  backend/src/server/routes/v1/admin-router.ts
  backend/src/server/routes/v1/sso-router.ts
  backend/src/services/super-admin/super-admin-service.ts
Labels: 🐞 bug, 🧨 backend

#1375 feat: github workflow for api diff check, ts check and lint check on PR
  .github/workflows/check-api-for-breaking-changes.yml
  .github/workflows/check-be-pull-request.yml
  .github/workflows/check-be-ts-and-lint.yml
  docker-compose.pg.yml
Labels: 🧨 backend, chore

#1369 feat: added guides for new backend development
  .env.migration.example
  .gitignore
  backend/scripts/generate-schema-types.ts
  backend/src/db/knexfile.ts
  docs/contributing/platform/backend/folder-structure.mdx
  docs/contributing/platform/backend/how-to-create-a-feature.mdx
  docs/mint.json
Labels: chore

#1387 chore: changed mintlify to directly get from prod openapi
  backend/src/db/knexfile.ts
  backend/src/ee/routes/v1/project-router.ts
  backend/src/ee/routes/v1/snapshot-router.ts
  backend/src/server/plugins/swagger.ts
  backend/src/server/routes/v1/admin-router.ts
  backend/src/server/routes/v1/identity-access-token-router.ts
  backend/src/server/routes/v1/identity-router.ts
  backend/src/server/routes/v1/identity-ua.ts
  backend/src/server/routes/v1/project-env-router.ts
  backend/src/server/routes/v1/project-membership-router.ts
  backend/src/server/routes/v1/secret-folder-router.ts
  backend/src/server/routes/v1/secret-import-router.ts
  backend/src/server/routes/v2/identity-org-router.ts
  backend/src/server/routes/v2/identity-project-router.ts
  backend/src/server/routes/v2/organization-router.ts
  backend/src/server/routes/v2/project-router.ts
  backend/src/server/routes/v2/service-token-router.ts
  backend/src/server/routes/v2/user-router.ts
  backend/src/server/routes/v3/secret-router.ts
  docs/api-reference/endpoints/environments/create.mdx
  docs/api-reference/endpoints/environments/delete.mdx
  docs/api-reference/endpoints/environments/update.mdx
  docs/api-reference/endpoints/folders/create.mdx
  docs/api-reference/endpoints/folders/delete.mdx
  docs/api-reference/endpoints/folders/list.mdx
  docs/api-reference/endpoints/folders/update.mdx
  docs/api-reference/endpoints/identities/create.mdx
  docs/api-reference/endpoints/identities/delete.mdx
  docs/api-reference/endpoints/identities/update.mdx
  docs/api-reference/endpoints/organizations/list-identity-memberships.mdx
  docs/api-reference/endpoints/secret-imports/create.mdx
  docs/api-reference/endpoints/secret-imports/delete.mdx
  docs/api-reference/endpoints/secret-imports/list.mdx
  docs/api-reference/endpoints/secret-imports/update.mdx
  docs/api-reference/endpoints/service-tokens/get.mdx
  docs/api-reference/endpoints/workspaces/delete-identity-membership.mdx
  docs/api-reference/endpoints/workspaces/delete-membership.mdx
  docs/api-reference/endpoints/workspaces/list-identity-memberships.mdx
  docs/api-reference/endpoints/workspaces/memberships.mdx
  docs/api-reference/endpoints/workspaces/rollback-snapshot.mdx
  docs/api-reference/endpoints/workspaces/update-identity-membership.mdx
  docs/api-reference/endpoints/workspaces/update-membership.mdx
  docs/mint.json
  docs/spec.yaml
Labels: chore

#1385 feat: changed docker compose to use init container pattern for running migration
  .env.example
  Makefile
  docker-compose.dev.yml
  docker-compose.pg.yml
  docker-compose.prod.yml
Labels: chore

#1418 fix: resolved secret import secrets failing when folder has empty secrets
  backend/src/services/secret-import/secret-import-fns.ts
Labels: 🐞 bug

#1408 Integration test for secret ops
  .env.test.example
  .github/workflows/release-standalone-docker-img-postgres-offical.yml
  .github/workflows/run-backend-tests.yml
  backend/.eslintignore
  backend/.eslintrc.js
  backend/e2e-test/routes/v1/identity.spec.ts
  backend/e2e-test/routes/v1/login.spec.ts
  backend/e2e-test/routes/v1/project-env.spec.ts
  backend/e2e-test/routes/v1/secret-folder.spec.ts
  backend/e2e-test/routes/v1/secret-import.spec.ts
  backend/e2e-test/routes/v2/service-token.spec.ts
  backend/e2e-test/routes/v3/secrets.spec.ts
  backend/e2e-test/vitest-environment-knex.ts
  backend/package-lock.json
  backend/package.json
  backend/scripts/create-seed-file.ts
  backend/src/db/knexfile.ts
  backend/src/db/seed-data.ts
  backend/src/db/seeds/1-user.ts
  backend/src/db/seeds/2-org.ts
  backend/src/db/seeds/3-project.ts
  backend/src/db/seeds/4-machine-identity.ts
  backend/src/ee/services/license/__mocks__/licence-fns.ts
  backend/src/lib/crypto/encryption.ts
  backend/src/server/app.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/secret/secret-dal.ts
  backend/vitest.e2e.config.ts
Labels: e2e-api-test

#1442 chore: added type and lint check for frontend ci/cd
  .github/workflows/check-fe-ts-and-lint.yml
Labels: 💥 CI/CD, chore

#1443 fix(telemetry): added back email for telemetry when using service token
  backend/src/ee/routes/v1/scim-router.ts
  backend/src/ee/services/permission/permission-service.ts
  backend/src/server/plugins/auth/inject-identity.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/service-token/service-token-dal.ts
  backend/src/services/service-token/service-token-service.ts
Labels: 🧨 backend

#1446 (Fix): Project upgrade
  backend/src/services/project-membership/project-membership-service.ts
  backend/src/services/project/project-fns.ts
  backend/src/services/project/project-queue.ts
  docs/api-reference/endpoints/workspaces/create-workspace.mdx
  docs/api-reference/endpoints/workspaces/delete-workspace.mdx
  docs/api-reference/endpoints/workspaces/get-workspace.mdx
  docs/api-reference/endpoints/workspaces/update-workspace.mdx
  frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
Labels: 🐞 bug, 📑 documentation

#1447 (style): Show upgrade alert to all users
  frontend/src/components/v2/UpgradeOverlay/UpgradeOverlay.tsx
  frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx
Labels: 💻 code improvements

#1444 feat(telemetry): added new telemetry events
  backend/src/server/lib/telemetry.ts
  backend/src/server/routes/index.ts
  backend/src/server/routes/v1/identity-router.ts
  backend/src/server/routes/v1/integration-router.ts
  backend/src/server/routes/v1/invite-org-router.ts
  backend/src/server/routes/v2/project-router.ts
  backend/src/server/routes/v3/secret-router.ts
  backend/src/services/telemetry/telemetry-service.ts
  backend/src/services/telemetry/telemetry-types.ts
Labels: 🧨 backend

#1484 feat(ui): secret blind index banner in secret main page and removed i18n to keep only english for now
  frontend/src/i18n.ts
  frontend/src/views/SecretMainPage/SecretMainPage.tsx
  frontend/src/views/Settings/PersonalSettingsPage/PersonalGeneralTab/PersonalGeneralTab.tsx
Labels: 👀 frontend

#1492 fix(server): resolved broken create tag scoped to project
  backend/src/services/secret-tag/secret-tag-service.ts
Labels: 🐞 bug, 🧨 backend

#1494 fix(pg-migrator): added uuid 0000 for admin config
  pg-migrator/src/index.ts
Labels: 🐞 bug

#1493 fix(server): duplicate secret deletion made possible
  backend/src/services/secret/secret-service.ts
Labels: 🐞 bug, 🧨 backend
